name: lint
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v3
      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
