name: test
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.14, 1.15 ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}
      - name: Run tests
        run: go test -v -covermode=count
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Calc coverage
        run: |
          go test -v -covermode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.8
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{secrets.github_token}}
          path-to-lcov: coverage.lcov
