name: test
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  test:
    strategy:
      matrix:
        go-version: [ 1.14, 1.15 ]
        platform: [ ubuntu-latest, macos-latest ]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Setup go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}
      - uses: actions/checkout@v2
      - name: Run tests
        run: go test -v -covermode=count
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/ckeckout@v2
      - name: Cala coverage
        run: |
          go test -v -coveragemode=count -coverprofile=coverage.out
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.6
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
